# Generated by Django 5.1 on 2024-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.TextField(default='Contenu par défaut'),
        ),
        migrations.AddField(
            model_name='articles',
            name='date_pub',
            field=models.DateTimeField(null=True),
        ),
    ]
